### PR TITLE
feat: Null safety.

### PR DESCRIPTION
**Pull request by dees91**
Hi, as flutter 2.0 is released I've made implementation for null safety support.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@dees91 thanks for this. Why are there so many format changes? Is it your IDE or it was you?

**Comment by robertohuertasm** [comment]
I think it would be better to publish the nullsafety as a pre-release to avoid breaking changes. I'll keep you posted.

**Comment by hyungtaecf** [comment]
What is the status of this?

**Comment by sharpner** [comment]
I would also love to know :-)

**Comment by robertohuertasm** [comment]
@dees91 I'm trying to push to your branch to fix the format issues but it seems you don't have this enabled. I'll merge this and fix it in another PR. Thanks for your contribution.

**Comment by robertohuertasm** [comment]
We'll try to release it today. We have to fix the formatting and change the pipelines to GitHub Actions. Stay tuned.

**Pull request merged**
